#pragma once

#if defined(ARDUINO_ARCH_ESP32)

#include <components/LoRa/e220.h>
#include <library/wobc.h>

namespace component {

// LoRa1 half-duplex link.
// Ground sends commands and receives ACKs; Flight receives commands and sends
// the execution ACK generated by the destination component.
class Uplink : public process::Component {
public:
  static constexpr uint8_t component_id = 0x10;

  enum class Role : uint8_t { Ground, Flight };

  struct RadioConfig {
    unsigned uart_number;
    pin_t aux, m0, m1, uart_rx, uart_tx, rf_switch_1, rf_switch_2;
    uint8_t channel;
  };

  Uplink(const RadioConfig& config, Role role, uint8_t flight_unit_id);

protected:
  void setup() override;
  void loop() override;

private:
  enum class RadioSetup : uint8_t {
    OK,
    RX_BUFFER,
    BEGIN,
    CONFIG_MODE,
    CONFIG_READ,
    UART_BAUD,
    DATA_RATE,
    ENV_RSSI,
    SEND_MODE,
    ADDRESS,
    CHANNEL,
    PACKET_RSSI,
    NORMAL_MODE,
  };

  static const char* setupName(RadioSetup setup);
  RadioSetup configureRadio();
  void logResponse(unsigned baud);
  void receiveOne();
  void collectTxPackets();
  void serviceTx();
  bool enqueue(const wcpp::Packet& packet);
  wcpp::Packet dequeue();
  bool matchesInflightCommand(const wcpp::Packet& ack) const;

  static constexpr unsigned long lora_baud = 9600;
  static constexpr unsigned rssi_entry_size = 4;

  const RadioConfig config_;
  const Role role_;
  const uint8_t flight_unit_id_;
  HardwareSerial serial_;
  E220 radio_;
  kernel::Listener tx_listener_;

  static constexpr unsigned tx_queue_size = 8;
  struct TxQueue {
    wcpp::Packet packets[tx_queue_size] = {
        wcpp::Packet::null(), wcpp::Packet::null(),
        wcpp::Packet::null(), wcpp::Packet::null(),
        wcpp::Packet::null(), wcpp::Packet::null(),
        wcpp::Packet::null(), wcpp::Packet::null(),
    };
    unsigned head = 0;
    unsigned count = 0;
  } tx_queue_;

  wcpp::Packet pending_tx_ = wcpp::Packet::null();
  wcpp::Packet inflight_command_ = wcpp::Packet::null();
  RadioSetup radio_setup_ = RadioSetup::BEGIN;
  bool ready_ = false;
  bool tx_active_ = false;
  bool awaiting_ack_ = false;
  unsigned transmit_attempts_ = 0;
  uint32_t tx_started_ms_ = 0;
  uint32_t tx_hold_ms_ = 0;
  uint32_t last_activity_ms_ = 0;
  uint32_t ack_deadline_ms_ = 0;

  static constexpr uint32_t turnaround_guard_ms = 100;
  static constexpr uint32_t ack_timeout_ms = 5000;
  static constexpr unsigned max_transmit_attempts = 3;
};

}  // namespace component

#endif
